### ISSUE TITLE
Get buffer

### ISSUE THREAD

**Issue by xirf** [ItsHisoka17/Anime-Images-API-Wrapper#1]
can you add buffer responses?

**Comment by ItsHisoka17** [comment]
> can you add buffer responses?

This project is no longer maintained, but feel free to make a pull request and i'll look over it.

**Comment by gamersindo1223** [comment]
@xirf 
just do Buffer.from(axios.get(<INPUT THE URL>, {responseType: 'arraybuffer'}))
