### ISSUE TITLE
Endpoint issue

### ISSUE THREAD

**Issue by gamersindo1223** [ItsHisoka17/Anime-Images-API-Wrapper#2]
as per january Repl.it Removed all deployed project, now the url does not work

**Comment by ItsHisoka17** [comment]
> as per january Repl.it Removed all deployed project, now the url does not work
> 
> This project is no longer maintained. The cdn server and content still exists and I will be creating a new API for this in the near future. I aplogize for this.

**Comment by ItsHisoka17** [comment]
**This project is no longer maintained and is shut down.** 
The cdn server and content still exists and I will be creating a new API for this in the near future. I apologize for this.

**Comment by gamersindo1223** [comment]
@ItsHisoka17 Is there anyways to get the images? using the cdn
